name: life_research
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.6.1 
  firebase_core: ^2.12.0
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  image_picker: ^0.8.7+5
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/LifeImage.webp

