// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMCftOZKXYYzpFoeHkQVi2p8PNqt8GWoI',
    appId: '1:437697743354:android:e32f7bbc39c1524f16fc43',
    messagingSenderId: '437697743354',
    projectId: 'life-research-6dbad',
    storageBucket: 'life-research-6dbad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3gYP6qyTgwQ6ZnX9x67GzGjdxZ7lJoCQ',
    appId: '1:437697743354:ios:2314912db342895216fc43',
    messagingSenderId: '437697743354',
    projectId: 'life-research-6dbad',
    storageBucket: 'life-research-6dbad.appspot.com',
    androidClientId: '437697743354-i51qtq0hv0bqnujdk2i348ku2s071lur.apps.googleusercontent.com',
    iosClientId: '437697743354-s7jvjrt9cid4h61eekt5s8g0h8gqoj8b.apps.googleusercontent.com',
    iosBundleId: 'com.jsw.lifeResearch',
  );
}
